'use strict';

const session = require('express-session');
const { cookieAttributes } = require('./sessionConfig');

/**
 * express-session wired the way the product needs it:
 *  - saveUninitialized:false  anonymous visitors get no cookie and no row
 *  - resave:false             sessions are only written when they change
 *  - rolling:false            the cookie is NOT re-issued on every response; its
 *                             lifetime is the absolute limit (30 days) and the
 *                             idle limit is enforced server-side by the store
 *  - secret                   signs the cookie; an array supports rotation (the
 *                             first entry signs, all entries verify)
 * The session id itself is a random 192-bit value generated by the library.
 */
function createSessionMiddleware({ store, config }) {
  return session({
    name: config.cookieName,
    secret: config.secrets,
    store,
    resave: false,
    saveUninitialized: false,
    rolling: false,
    cookie: { ...cookieAttributes(config), maxAge: config.absoluteTtlMs },
  });
}

module.exports = { createSessionMiddleware };
